# services:
#   web:
#     build: .
#     container_name: express-80-443
#     restart: unless-stopped
#     volumes:
#       - ./certs:/certs:ro
#     ports:
#       - "80:80"
#       - "443:443"

services:
  web:
    build: .
    container_name: demo_simple-web
    restart: unless-stopped
    environment:
      - DOMAIN=geocampo.online
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Certs solo lectura para la app
      - ./certbot/conf:/etc/letsencrypt:ro
      # Webroot ACME solo lectura para la app
      - ./certbot/www:/var/www/certbot:ro

  # Emisión inicial (se corre MANUAL una sola vez)
  certbot_once:
    image: certbot/certbot:latest
    container_name: demo_simple-certbot-once
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >
      certonly --webroot
      --webroot-path /var/www/certbot
      -d geocampo.online
      --email TU_EMAIL@correo.com
      --agree-tos
      --no-eff-email

  # Renovación automática (sin docker CLI; usando API del daemon)
  certbot_renew:
    image: certbot/certbot:latest
    container_name: demo_simple-certbot-renew
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/sh
    command: |
      -c '
      set -e
      # Instalar curl si falta (funciona en Alpine o Debian)
      if ! command -v curl >/dev/null 2>&1; then
        (apk add --no-cache curl) 2>/dev/null || (apt-get update && apt-get install -y curl)
      fi
      while :; do
        certbot renew --webroot -w /var/www/certbot \
          --deploy-hook "curl --unix-socket /var/run/docker.sock -s -o /dev/null -w %{http_code} -X POST http://localhost/v1.43/containers/demo_simple-web/restart" \
          --disable-hook-validation ;
        sleep 12h ;
      done
      '
