services:
  web:
    build: ./Server
    container_name: demo_simple-web
    restart: unless-stopped
    environment:
      - DOMAIN=geocampo.online
      - PHP_TARGET=http://php:3001
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro

  php:
    image: php:8.3-cli
    container_name: demo_simple-php
    working_dir: /app
    command: php -S 0.0.0.0:3001 -t /app
    volumes:
      - ./PHP:/app:ro
    expose:
      - "3001"

  # Emisión inicial (se corre MANUAL una sola vez)
  certbot_once:
    image: certbot/certbot:latest
    container_name: demo_simple-certbot-once
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >
      certonly --webroot
      --webroot-path /var/www/certbot
      -d geocampo.online
      --email dalayo@cobranzasperu.com
      --agree-tos
      --no-eff-email

  # Renovación automática (sin docker CLI; usando API del daemon)
  certbot_renew:
    image: certbot/certbot:latest
    container_name: demo_simple-certbot-renew
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/sh
    command: |
      -c '
      set -e
      # Instalar curl si falta (funciona en Alpine o Debian)
      if ! command -v curl >/dev/null 2>&1; then
        (apk add --no-cache curl) 2>/dev/null || (apt-get update && apt-get install -y curl)
      fi
      while :; do
        certbot renew --webroot -w /var/www/certbot \
          --deploy-hook "curl --unix-socket /var/run/docker.sock -s -o /dev/null -w %{http_code} -X POST http://localhost/v1.43/containers/demo_simple-web/restart" \
          --disable-hook-validation ;
        sleep 12h ;
      done
      '
